[package]
name = "commons"
version = "0.3.3"
edition = "2021"
description = "Common libraries for DLMM"
authors = ["tian <tian@racoons.dev>"]

[features]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
bincode.workspace = true
bytemuck = { workspace = true, features = ["derive", "min_const_generics"] }
dlmm.workspace = true
solana-account.workspace = true
solana-client.workspace = true
solana-pubkey.workspace = true
solana-clock.workspace = true
spl-transfer-hook-interface = { workspace = true }
tokio = { workspace = true, features = ["full", "parking_lot"] }
solana-instruction.workspace = true
url = "2.5.8"

[dev-dependencies]
litesvm = "0.13.1"
assert_matches = "1.5.0"
serde_json = { workspace = true }
solana-program.workspace = true
solana-program-test = "^3.0.0"
spl-associated-token-account = { workspace = true }
spl-memo = { workspace = true, features = ["no-entrypoint"] }
solana-keypair = "3.1.2"
